version: "2"

services:
  voting-app:
    build: ./docker-birthday-3-boot-voting/.
    container_name: vottingApp
    volumes:
     - ./docker-birthday-3-boot-voting:/app
    ports:
      - "4000:8080"
    networks:
      - back-tier

  worker-app:
    build: ./docker-birthday-3-boot-worker/.
    container_name: workerApp
    ports:
      - "3000:8080"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  ubuntu:
    image: ubuntu:14.04
    container_name: ubuntu
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
