FROM java:8

MAINTAINER jbbarquero@gmail.com

ADD target/docker-birthday-3-boot-voting-0.0.1-SNAPSHOT.jar /

ENTRYPOINT ["java", "-jar", "/docker-birthday-3-boot-voting-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080